### ISSUE TITLE
Threading issue?

### ISSUE THREAD

**Issue by alienxp03** [krimpedance/KRProgressHUD#10] opened 2016-07-19 15:17 UTC
Found some bug. Basically this is the flow to reproduce it on my end.

1. Start the app with `rootViewController` `viewControllerA`
2. Call `KRProgressHUD.show()`
3. Do something
4. Call `KRProgressHUD.dismiss()`
5. Call `UIApplication.sharedApplication().keyWindow?.rootViewController = viewControllerB`
6. On `viewControllerB`, tap a button that will trigger `KRProgressHUD.show()`.
7. The app somehow will show back `viewControllerA`. And no `KRProgressHUD` is shown anymore

So far that's how I reproduce it. If you need extra information just let me know. I'll see if I can create a sample app to show reproduce it.

**Comment by krimpedance** [comment] 2016-07-19 15:54
Sorry :(
There is not much doubt about the cause of the bug.
I will respond to that right away.

**Comment by krimpedance** [comment] 2016-07-19 16:18
I fixed the bug and released as 1.5.1 :)

Thank you for using KRProgressHUD.

**Closed by krimpedance** 2016-07-19 16:18 UTC
Labels: bug

**Comment by alienxp03** [comment] 2016-07-19 16:21
Thanks for the quick update! :)
