### ISSUE TITLE
Issue with window.addsubview

### ISSUE THREAD

**Issue by DanielLe232** [krimpedance/KRProgressHUD#19] opened 2016-10-25 08:02 UTC
When using this library, I can not add subview with UIApplication.shared.keyWindow?.addSubview
it shows and hides suddenly

**Comment by krimpedance** [comment] 2016-10-25 11:27
This library uses UIWindow.

I think the phenomenon occurs because `keyWindow` is being replaced when indicating this.

`addSubview` method should call before `show()` or after `dismiss()`.

**Comment by DanielLe232** [comment] 2016-10-26 02:05
Yup,
I have test if call addSubview method before show(), it ok
but call it after dismiss(), it fails

**Comment by krimpedance** [comment] 2016-10-26 04:05
Oh...
Which version do you use? (Swift, KRProgressHUD, Xcode)
And, which do you use Cocoapods or Carthage?

**Comment by krimpedance** [comment] 2016-10-26 04:18
Hey, I probably found out the cause !
Aren't you writing it as follows?
```
KRProgressHUD.dismiss()
view.addSubview(subview)
```
After KRProgressHUD disappeared **perfectly**, you should add subviews to KeyWindow.
```
KRProgressHUD.dismiss() {
  // Completion handler
  self.view.addSubview(subview)
}
```

**Comment by DanielLe232** [comment] 2016-10-26 07:47
My case:
get data from the server and show it on a table view
after finish load data from the server (KRProgressHUD.show() and KRProgress.dismiss() finish too), I click a row to add subview, it occurs an issue at here
I try your idea but it still occurs

**Comment by krimpedance** [comment] 2016-10-26 08:06
Please tell me.
> Which version do you use? (Swift, KRProgressHUD, Xcode)
> And, which do you use Cocoapods or Carthage?

I want you to show me a related partial program.

**Comment by DanielLe232** [comment] 2016-10-26 08:27
I use swift 3.0, xcode 8 and Cocoapods.

**Comment by krimpedance** [comment] 2016-10-26 08:35
What is KRProgressHUD's version.

**Comment by DanielLe232** [comment] 2016-10-26 08:56
KRProgressHUD 2.1.0

**Comment by krimpedance** [comment] 2016-10-26 09:34
Sorry, I can't reproduce its situation.
Can't you think the other cause such as `Thread`?

What is KeyWindow?
- When you show HUD
- When you dismiss HUD
- When you dismiss HUD (completion handler)
- When you click a row to add subview

Is it possible that you show me a code?

**Comment by DanielLe232** [comment] 2016-10-26 10:17
You could new project with table view in view controller
1. use KRProgressHUD for get data from server (or anywhere) and show on table view
===> func getData() {
      KRProgressHUD.show()
      API.getdatafromserver() {
            KRProgressHUD.dismiss()
            tableview.reloadData()
       }
}
2.When finish to show data on table view, we click on row to add subview
let viewH = UIView(frame: CGRect(x: 0, y: 0, w: view.w, h: view.h))
UIApplication.shared.keyWindow?.addSubview(viewH)

**Comment by krimpedance** [comment] 2016-10-26 11:02
Thanks.
Please try this.
I seem to have settled it with this.
```
func getData() {
  KRProgressHUD.show()
  API.getDataFromServer() {
    KRProgressHUD.dismiss() {
      tableview.reloadData()
    }
  }
}
```

**Comment by krimpedance** [comment] 2016-10-26 11:09
or
```swift
func getData() {
  KRProgressHUD.show()
  API.getDataFromServer() {
    // Maybe, other thread.
    KRProgressHUD.dismiss()
    DispatchQueue.main.async {
    // Main thread
      tableview.reloadData()
    }
  }
}
```

**Comment by DanielLe232** [comment] 2016-10-27 02:15
It still not working :(
Could you show me a source code.

**Comment by krimpedance** [comment] 2016-10-27 04:06
```swift
func getData() {
  KRProgressHUD.show()
  API.getDataFromServer() {
    // Maybe, other thread.
    KRProgressHUD.dismiss() {
    // Main thread
      tableview.reloadData()
    }
  }
}

func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
  tableView.deselectRow(at: indexPath, animated: true)        
  let sv = UIView(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: self.view.frame.height))
  sv.backgroundColor = .red
  UIApplication.shared.keyWindow?.addSubview(sv)
}
```

**Comment by krimpedance** [comment] 2016-11-07 19:22
I close this issue because @DanielLe232 is no reaction.

**Closed by krimpedance** 2016-11-07 19:22 UTC
